name: property_pulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # UTILITIES
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.1   
  intl: ^0.19.0

  # GOOGLE MAPS
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0

  # THEME + SETTINGS
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # PROFILE PICTURE
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env